version: '3.8'

services:
  db:
    image: postgres:latest
    env_file: '.env'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 20
    volumes:
      - ${PWD}/volumes/postgres:/var/lib/postgresql/data
  
  pgloader:
    image: dimitri/pgloader
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app/data:/data
    command: >
      sh -c "sleep 5 && pgloader sqlite:///data/places.db postgresql://postgres:postgres@db:5432/places"