services:
  db:
    image: postgres:latest
    env_file: '.env'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 20
    volumes:
      - ${PWD}/volumes/postgres:/var/lib/postgresql/18/docker
    networks:
      - service_network

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - service_network

networks:
  service_network:
    driver: bridge